// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2ot6wNGeyMnFdRKLBdEqjCjsIWTjUvc',
    appId: '1:421628538374:web:3f4426684103f5c9965d87',
    messagingSenderId: '421628538374',
    projectId: 'enviropulse-8c717',
    authDomain: 'enviropulse-8c717.firebaseapp.com',
    storageBucket: 'enviropulse-8c717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARM7LiKhtvFc53WLQfgh3ooX9WSYzab2c',
    appId: '1:421628538374:android:81446df759273f24965d87',
    messagingSenderId: '421628538374',
    projectId: 'enviropulse-8c717',
    storageBucket: 'enviropulse-8c717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-eVPHro2md-siEMLX8FCSfRHt79fJt7E',
    appId: '1:421628538374:ios:0f7a6b80dec2dce5965d87',
    messagingSenderId: '421628538374',
    projectId: 'enviropulse-8c717',
    storageBucket: 'enviropulse-8c717.firebasestorage.app',
    iosBundleId: 'com.example.enviropulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc2ot6wNGeyMnFdRKLBdEqjCjsIWTjUvc',
    appId: '1:421628538374:web:7bcd17ec1b3bb83f965d87',
    messagingSenderId: '421628538374',
    projectId: 'enviropulse-8c717',
    authDomain: 'enviropulse-8c717.firebaseapp.com',
    storageBucket: 'enviropulse-8c717.firebasestorage.app',
  );
}
